[workspace]
resolver = "2"
members = [
    "crates/embrig-core",
    "crates/embrig-dbc",
    "crates/embrig-models",
    "crates/embrig-can",
    "crates/embrig-test",
    "crates/embrig-sil",
    "crates/embrig-net",
    "crates/embrig-cli",
    "firmware/controller",
    "firmware/robot",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
repository = "https://github.com/DavidNeurieder/embrig"

[workspace.dependencies]
embrig-core = { path = "crates/embrig-core" }
embrig-dbc = { path = "crates/embrig-dbc" }
embrig-models = { path = "crates/embrig-models" }
embrig-can = { path = "crates/embrig-can" }
embrig-test = { path = "crates/embrig-test" }
embrig-sil = { path = "crates/embrig-sil" }
embrig-net = { path = "crates/embrig-net" }

fw-controller = { path = "firmware/controller" }
fw-robot = { path = "firmware/robot" }

serde = "1.0.229"
serde_json = "1.0"
serde-saphyr = "1.0.1"
thiserror = "2.0.19"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "sync", "net"] }
clap = { version = "4.6.6", features = ["derive"] }
anyhow = "1.0.104"
socketcan = { version = "3.6.2", features = ["tokio"] }

[profile.release]
lto = true
