[package]
name = "openhil-test"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
openhil-core = { workspace = true }
openhil-dbc = { workspace = true }
openhil-models = { workspace = true }
openhil-can = { workspace = true }
serde = { workspace = true }
serde-saphyr = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }

[features]
default = []
socketcan = ["openhil-can/socketcan"]
