[package]
name = "embrig-models"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
embrig-core = { workspace = true }
embrig-dbc = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde-saphyr = { workspace = true }
thiserror = { workspace = true }
