[package]
name = "openhil-models"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
openhil-core = { workspace = true }
openhil-dbc = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde-saphyr = { workspace = true }
thiserror = { workspace = true }
