[package]
name = "embrig-test"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
embrig-core = { workspace = true }
embrig-dbc = { workspace = true }
embrig-models = { workspace = true }
embrig-can = { workspace = true }
embrig-net = { workspace = true }
serde = { workspace = true }
serde-saphyr = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }

[features]
default = []
socketcan = ["embrig-can/socketcan"]
